export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  FINANCE_ADMIN: 'finance_admin',
  SUPPORT_ADMIN: 'support_admin',
  USER: 'user',
} as const;

export type Role = typeof ROLES[keyof typeof ROLES];

export const PERMISSIONS = {
  VIEW_STATS: [ROLES.SUPER_ADMIN, ROLES.FINANCE_ADMIN],
  MANAGE_USERS: [ROLES.SUPER_ADMIN, ROLES.SUPPORT_ADMIN],
  MANAGE_PRODUCTS: [ROLES.SUPER_ADMIN, ROLES.SUPPORT_ADMIN],
  MANAGE_PAYMENTS: [ROLES.SUPER_ADMIN, ROLES.FINANCE_ADMIN],
  MANAGE_TOPUPS: [ROLES.SUPER_ADMIN, ROLES.FINANCE_ADMIN, ROLES.SUPPORT_ADMIN],
  VIEW_REPORTS: [ROLES.SUPER_ADMIN, ROLES.FINANCE_ADMIN],
  MANAGE_PROVIDERS: [ROLES.SUPER_ADMIN],
};
